# --> dayfox (light)
set -g @thm_bg "#f6f2ee" # bg0 (status line)
set -g @thm_fg "#3d2b5a" # fg1 (default fg)
set -g @thm_black "#352c24" # black
set -g @thm_gray "#d3c7bb" # bg3 (color0)
set -g @thm_red "#a5222f" # red
set -g @thm_green "#396847" # green
set -g @thm_yellow "#AC5402" # yellow
set -g @thm_blue "#2848a9" # blue
set -g @thm_pink "#a440b5" # pink
set -g @thm_cyan "#287980" # cyan
set -g @thm_orange "#955f61" # orange
set -g @thm_overlay_0 "#837a72" # comment (separators)
set -g @thm_surface_0 "#dbd1dd" # bg2 (borders)
set -g @thm_maroon "#a5222f" # command
set -g @thm_mauve "#6e33ce" # magenta (online)
set -g @thm_rosewater "#643f61" # fg2 (inactive window)
set -g @thm_peach "#2848a9" # blue (active/last window)

set -g @catppuccin_flavor "latte"
