# --> carbonfox (dark)
set -g @thm_bg "#161616" # background
set -g @thm_fg "#f2f4f8" # foreground
set -g @thm_black "#0c0c0c" # active_tab_foreground
set -g @thm_gray "#282828" # color0
set -g @thm_red "#ee5396" # color1
set -g @thm_green "#25be6a" # color2
set -g @thm_yellow "#08bdba" # color3
set -g @thm_blue "#78a9ff" # color4
set -g @thm_pink "#be95ff" # color5
set -g @thm_cyan "#33b1ff" # color6
set -g @thm_orange "#ff7eb6" # color17
set -g @thm_overlay_0 "#525253" # separators
set -g @thm_surface_0 "#282828" # borders
set -g @thm_maroon "#ee5396" # command
set -g @thm_mauve "#be95ff" # online
set -g @thm_rosewater "#f2f4f8" # inactive window
set -g @thm_peach "#ff7eb6" # active/last window

set -g @catppuccin_flavor "mocha"
